# Generated by Django 5.1.4 on 2025-01-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('release_year', models.TextField()),
                ('director', models.TextField()),
                ('cast', models.TextField()),
                ('genre', models.TextField()),
                ('rating', models.TextField()),
                ('running_time', models.TextField()),
                ('review_content', models.TextField()),
            ],
        ),
    ]
